

echo "The script will remove all openstack related softwares, packages and configurations in your machine" 
read -p "Are you sure to do that? Y/n" choice

[ $choice != "Y" ] && exit 0;

# Destroy VMs
for x in $(virsh list --all | grep instance- | awk '{print $2}') ; do
    virsh destroy $x ;
    virsh undefine $x ;
done ;

echo "Unmount cinder blocks..."
umount /srv/node/device* ;
killall -9 dnsmasq tgtd httpd ;
setenforce 1 ;
vgremove -f cinder-volumes ;
losetup -a | sed -e 's/:.*//g' | xargs losetup -d ;
find /etc/pki/tls -name "ssl_ps*" | xargs rm -rf ;
for x in $(df | grep "/lib/" | sed -e 's/.* //g') ; do
    umount $x ;
done


# Remove installed packages
yum remove -y nrpe "*nagios*" puppet "*ntp*" "*openstack*" "*horizon*" \
"*nova*" "*keystone*" "*glance*" "*cinder*" "*swift*" "*neutron*" \
"ceilometer" "*mysql*" httpd "*memcache*" scsi-target-utils \
iscsi-initiator-utils perl-DBI perl-DBD-MySQL rdo-release \
"*qpid*" "*rabbitmq*" "*trove*";

#"*python-oslo*" "*python-six*" \
#"*python-croniter*" "*python-crypto*" "*python-flask*" "*python-networkx*" \
#"*python-oauthlib*" "*python-paramiko*" "*python-pecan*" "*python-pycadf*" "*python-singledispatch*" \
#"*python-taskflow*" "*python-troveclient*" "*python-wsme*";

ps -ef | grep -i repli | grep swift | awk '{print $2}' | xargs kill ;

# Delete local application data
echo "Cleaning configuration files..."
rm -rf /etc/nagios /etc/yum.repos.d/packstack_* /root/.my.cnf /root/.novaclient\
/etc/nova /etc/swift /etc/openstack-dashboard/ /etc/neutron/ \
/etc/httpd/ /etc/rabbitmq/ /etc/keystone /etc/ceilometer /etc/my.cnf.d/ /etc/mysql \
/etc/glance \
 /usr/share/openstack-dashboard

echo "Cleaning lib files..."
rm -rf /var/lib/mysql/ /var/lib/glance /var/lib/nova  \
/srv/node/device*/* /var/lib/cinder/ /var/lib/neutron/ /var/lib/ceilometer \
/var/lib/openstack-dashboard/ /etc/rsync.d/frag* /var/cache/swift /var/lib/rabbitmq \
/var/lib/keystone/

echo "Cleaning log files..."
rm -rf /var/log/keystone /var/log/cinder/ /var/log/nova/ \
/var/log/horizon/ /var/log/httpd /var/log/glance/ /var/log/nagios/ \
/var/log/neutron/

echo "Cleaning runtime files..."
rm -rf var/lock/subsys/neutron-* /var/run/neutron /var/run/horizon /var/run/cinder/ /var/run/glance

echo "Cleaning executive files..."
rm /usr/bin/openstack* /var/www/keystone /usr/bin/keystone*

# Delete created bridges
ovs-vsctl --if-exists del-port br-int patch-tun
ovs-vsctl --if-exists del-port br-tun patch-int
ovs-vsctl --if-exists del-port br-tun gre-1
ovs-vsctl --if-exists del-port br-tun gre-2
ovs-vsctl --if-exists del-br br-tun
ovs-vsctl del-controller br-int
ovs-vsctl --if-exists del-br br-int

# Clean the iptables rules generated by openstack
iptables -P INPUT ACCEPT
iptables -F
iptables -X
iptables -Z
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j ACCEPT #ssh
iptables -A INPUT -p tcp --dport 80 -j ACCEPT #ssh
iptables -A INPUT -p tcp -m state --state NEW -m tcp -m multiport --dports 5901:5903,6001:6003 -j ACCEPT #VNC/X-window
iptables -A INPUT -j REJECT --reject-with icmp-host-prohibited
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -A FORWARD -j REJECT --reject-with icmp-host-prohibited
iptables -P OUTPUT ACCEPT

service iptables save
if [ -f /etc/sysconfig/iptables ]; then
    sed -i '/nova/d' /etc/sysconfig/iptables 
    sed -i '/neutron/d' /etc/sysconfig/iptables 
fi
service iptables restart

# clean all generated network namespace
for name in `ip netns show`  
do
    [[ $name == qdhcp-* || $name == qrouter-* ]] &&  ip netns del $name
done

#yum clean all; yum makecache; yum -y update
